name: Copy S3 Objects on Pull Request

on:
  pull_request:
    branches:
      - main

jobs:
  copy-s3:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v2.5.2  # Ensure to use the latest version
      with:
        python-version: '3.8'  # Specify your Python version here

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install boto3

    - name: Run copy script
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      run: |
        python .github/scripts/copy_s3_objects.py  # Adjust the path to your script if necessary
